# Generated by Django 3.0.5 on 2020-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=False)),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Noturno')], max_length=1)),
            ],
        ),
    ]
