# Generated by Django 3.0.5 on 2020-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
